name: operations-research-notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  # python
  - python=3.7.6
  - ipykernel=6.4.1
  # r - uncomment to include R
  # - r-base=3.6.1
  # - r-irkernel=0.8.15
