name: operations-research-notebooks

channels:
  - conda-forge
  - defaults

dependencies:
  - python

  # Jupyter
  - ipykernel
  - ipywidgets

  # Data Engineering
  - pandas
  - s3fs
  - pyarrow
  - fastparquet
  - python-snappy
  - python-dotenv
  - pydantic

  # Data Analysis
  - scikit-learn
  - shapely
  - geopandas
  - scipy

  # Operations Research
  - pyomo
  - ipopt

  # Visualizations
  - matplotlib
  - seaborn
  - missingno

  # Misc
  - bs4
  - lxml
  - ca-certificates
  - certifi
  - openssl
  - fsspec

  # Testing and Code Quality
  - autopep8
  - pylint
  - pytest
